apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-client
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["*"]
- apiGroups: ["damnvulerable.io"]
  resources: ["configurablepods"]
  verbs: ["*"]
