apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-controller
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-{{ .Chart.Name }}-controller
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-{{ .Chart.Name }}-controller
  apiGroup: rbac.authorization.k8s.io
