apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-controller
rules:
- apiGroups: [""]
  resources: ["secrets", "pods"]
  verbs: ["*"]
- apiGroups: ["damnvulerable.io"]
  resources: ["configurablepods"]
  verbs: ["*"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["*"]
