apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-controller
  labels:
    app: {{ .Release.Name }}-{{ .Chart.Name }}-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Chart.Name }}-controller
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Chart.Name }}-controller
    spec:
      serviceAccountName: {{ .Release.Name }}-{{ .Chart.Name }}-controller
      containers:
        - name: {{ .Release.Name }}-{{ .Chart.Name }}-controller
          image: ghcr.io/damnvulnerable/configurablepod:main
